export default [
  {
    id: "1",
    name: "Turnul intunecat",
    author: "Stephen King",
    publish: "Valdo",
    genre: "horror",
    cover: "2.jpg",
  },
  {
    id: "2",
    name: "Vrajitorul si Globul de Cristal",
    author: "Dean R. Koontz",
    publish: "Valdo",
    genre: "comedy",
    cover: "8.jpg",
  },
  {
    id: "3",
    name: "Cujo",
    author: "H.P. Lovecraft",
    publish: "Nemira",
    genre: "roamnce",
    cover: "5.jpg",
  },
  {
    id: "4",
    name: "Apocalipsa",
    author: "Agatha Christine",
    publish: "Kriterrion",
    genre: "romance",
    cover: "7.jpg",
  },
  {
    id: "5",
    name: "Pistolarul",
    author: "Mark Manson",
    publish: "Litera",
    genre: "action",
    cover: "6.jpg",
  },
  {
    id: "6",
    name: " Cantecul lui Susanah",
    author: "Kevin Duton",
    publish: "Kriterrion",
    genre: "horror",
    cover: "1.jpg",
  },
  {
    id: "7",
    name: "Ce-am gasit al meu sa fie",
    author: "Stephen King",
    publish: "Litera",
    genre: "thriller",
    cover: "4.jpg",
  },
  {
    id: "8",
    name: "If it bleeds",
    author: "Mark Manson",
    publish: "Nemira",
    genre: "drama",
    cover: "3.webp",
  },
];
